---
- name: Complete Server Configuration and Deployment
  hosts: web
  become: yes

  tasks:

    # System update
    - name: Update apt packages
      apt:
        update_cache: yes
      tags: update

    # Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: install

    # Start Nginx
    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      tags: start

    # Create file
    - name: Create a file
      file:
        path: /root/dipali.txt
        state: touch
        mode: '0644'
      tags: create
